language: java

sudo: false

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

cache:
  directories:
    - $HOME/.m2


script: ./mvnw clean verify

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
